Feature/1011
memonac/memonac-server pull request #10
Opened 2022-02-08 11:24 UTC by leesssuin

# [1011] {메모룸 상세 - 접속}

## 노션 칸반 링크
​
- [메모룸 상세 - 접속](https://www.notion.so/vanillacoding/back-5b76998f7bb64aa8adea4908785ab095)
​
## 카드에서 구현 혹은 해결하려는 내용
- 메모룸 처음 렌더링 시 get 요청에 대한 data 보내주기
- nodemailer
  - nodemailer setting
  - nodemailer에서 보낸 메일에 있는 링크 클릭하면 client에서 token 보내주고 그 보내준 token을 validation 한 후 db에 추가
​
## 기타 사항
- mongo server error 코드가 400번이 맞는것인지에 대한 논의 필요

2022-02-08 12:51 UTC, okcorn reviewed
고생하셨습니다 수인님!

2022-02-08 12:51 UTC, okcorn commented on controllers/nodemailer.js
> +    const url = `http://localhost:3000/${memoroomId}/invite?token=${token}`;
여기 url 환경변수 처리 해주시면 좋을 것 같습니다:)

2022-02-08 12:51 UTC, okcorn commented on configs/nodemailer.js
> +  port: 587,
환경변수 처리 부탁 드립니다!

2022-02-08 13:00 UTC, KongWooJeong requested changes

2022-02-08 13:00 UTC, KongWooJeong commented on controllers/nodemailer.js
> +    next(createHttpError(500, "Invalid Server Error"));
수인님 해당 에러 부분에서 nodeMailer에서 발생되는 에러도 잡아서 처리해주어야 할 것 같아요!!

2022-02-08 13:10 UTC, leesssuin commented on configs/nodemailer.js
> +  port: 587,
넵!

2022-02-08 13:10 UTC, leesssuin commented on controllers/nodemailer.js
> +    next(createHttpError(500, "Invalid Server Error"));
아.. 거기까지 생각하지 못했네요! 다시 수정해보겠습니다!

2022-02-08 13:11 UTC, leesssuin commented on controllers/nodemailer.js
> +    const url = `http://localhost:3000/${memoroomId}/invite?token=${token}`;
넵!

2022-02-08 13:40 UTC, leesssuin commented on configs/nodemailer.js
> +  port: 587,
음 지수님 그렇다면 저 server, host까지도 환경변수 처리해주는게 좋을까요?

2022-02-08 15:44 UTC, okcorn commented on configs/nodemailer.js
> +  port: 587,
네! 관련된 정보는 다 변수처리 해도 좋을 것 같습니다 ㅎㅎ

2022-02-09 10:10 UTC, okcorn approved these changes
네, 확인하였습니다 수인님 !

2022-02-09 10:21 UTC, KongWooJeong reviewed
수인님. 코멘트 확인 부탁드립니다!!

2022-02-09 10:21 UTC, KongWooJeong commented on controllers/nodemailer.js
> +  }
```suggestion    
    await transporter.sendMail(message);
    
    res.json({ result: "success" });
    return
  } catch (err) {
    if (err.code === "EENVELOPE") {
      res.status(400).json({
        result: "fail",
        error: {
          message: "Check the email",
        },
      });

      return;
    }
    
    if ("sendEmail 호출하였을때 발생되는 에러") {
      res.status(400).json({
        result: "fail",
        error: {
          message: "메일 발송 실패... "
        }
      });
    }

    return;
   
    next(createError(500, "Invalid Server Error"));
  }
```
콜백함수 말고 async await 를 사용하면 좋을것 같아요!!

위의 예시 코드 처럼 메일을 발송 실패 했을때 발생되는 에러도 잡아서 catch 문에 추가 하시면 좋을 것 같아요!!

2022-02-09 10:21 UTC, KongWooJeong commented on services/nodemailer.js
> +  return user;
```suggestion
  return await User.findOne({ email: email }).lean().exec();
```
별도의 변수 선언 없이 바로 return 하시는것 어떠신가요??

2022-02-09 10:31 UTC, leesssuin commented on controllers/nodemailer.js
> +  }
넵! 한번 수정해보겠습니다!

2022-02-09 10:31 UTC, leesssuin commented on services/nodemailer.js
> +  return user;
간결해져서 더 좋을것같아요! 수정해보겠습니다!

2022-02-09 11:41 UTC, KongWooJeong approved these changes
고생하셨습니다!!

2022-02-09 11:43 UTC, merged